description = "Hugo port of the Themefisher’s Educenter theme"
features = ["blog", "company", "responsive", "seo-friendly"]
homepage = "https://gethugothemes.com/products/educenter-hugo/"
license = "MIT"
licenselink = "https://github.com/themefisher/educenter-hugo/blob/master/LICENSE"
min_version = "0.70.0"
name = "Educenter Hugo"
tags = ["blog", "google-analytics", "fast", "modern", "minimal", "minimalistic", "business", "education", "white", "light", "multilingual", "bootstrap", "company", "portfolio", "projects", "responsive", "themefisher", "gethugothemes"]
[author]
homepage = "https://themefisher.com/"
name = "Themefisher"
[original]
homepage = "https://themefisher.com/products/education-template/"
name = "Educenter"
